// AUTH TYPES
export const SIGN_IN_REQUEST = "SIGN_IN_REQUEST";
export const SIGN_IN_SUCCEEDED = "SIGN_IN_SUCCEEDED";

export const SIGN_IN_FACEBOOK_REQUEST = "SIGN_IN_FACEBOOK_REQUEST";
export const SIGN_IN_FACEBOOK_SUCCEEDED = "SIGN_IN_FACEBOOK_SUCCEEDED";

export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST";
export const SIGN_UP_SUCCEEDED = "SIGN_UP_SUCCEEDED";

export const SIGN_OUT_REQUEST = "SIGN_OUT_REQUEST";
export const SIGN_OUT_SUCCEEDED = "SIGN_OUT_SUCCEEDED";
